/* PagesRunner — mounts design-project pages on their Webflow routes.
   Generated by build-pages-runner.js. Do not hand-edit.

   Two kinds of route:
     bespoke — the page has its own bundle exporting a component on window
     service — the page reuses ServiceDetailPage with a slug, data supplied by
               ServicesData + ServicesDataExtra

   Loaded site-wide via Project Settings -> Footer Code. Inserts #page-root if
   the Webflow page does not already provide one. */
(function () {
  if (window.__ignitePagesRunnerLoaded) return;
  window.__ignitePagesRunnerLoaded = true;

  var CDN = "https://kyle915.github.io/ignite-webflow-assets";
  var BESPOKE = {
    "/services/collegiate-marketing": {
      "global": "PageServicesCollegiateMarketing",
      "bundle": "PageServicesCollegiateMarketing",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/bilingual-brand-ambassadors": {
      "global": "PageServicesBilingualBrandAmbassadors",
      "bundle": "PageServicesBilingualBrandAmbassadors",
      "deps": [
        "RelatedCases",
        "MarketsData",
        "ServicesData",
        "ServiceDetail"
      ]
    },
    "/spark-retail": {
      "global": "PageSparkRetail",
      "bundle": "PageSparkRetail",
      "deps": [
        "SparkSite"
      ]
    },
    "/services/distributor-demo-programs": {
      "global": "PageServicesDistributorDemoPrograms",
      "bundle": "PageServicesDistributorDemoPrograms",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/on-premise-sampling": {
      "global": "PageServicesOnPremiseSampling",
      "bundle": "PageServicesOnPremiseSampling",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/shopper-marketing": {
      "global": "PageServicesShopperMarketing",
      "bundle": "PageServicesShopperMarketing",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/field-marketing": {
      "global": "PageServicesFieldMarketing",
      "bundle": "PageServicesFieldMarketing",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/mobile-tours": {
      "global": "PageServicesMobileTours",
      "bundle": "PageServicesMobileTours",
      "deps": [
        "RelatedCases"
      ]
    },
    "/brand-ambassador-agency": {
      "global": "PageBrandAmbassadorAgency",
      "bundle": "PageBrandAmbassadorAgency",
      "deps": []
    },
    "/services/retail-merchandising": {
      "global": "PageServicesRetailMerchandising",
      "bundle": "PageServicesRetailMerchandising",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/street-teams": {
      "global": "PageServicesStreetTeams",
      "bundle": "PageServicesStreetTeams",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/retail-demo-programs": {
      "global": "PageServicesRetailDemoPrograms",
      "bundle": "PageServicesRetailDemoPrograms",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/ai-management": {
      "global": "PageServicesAiManagement",
      "bundle": "PageServicesAiManagement",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/event-staffing": {
      "global": "PageServicesEventStaffing",
      "bundle": "PageServicesEventStaffing",
      "deps": [
        "RelatedCases",
        "AiCaseStudies"
      ]
    },
    "/spark-for-brands": {
      "global": "PageSparkForBrands",
      "bundle": "PageSparkForBrands",
      "deps": [
        "SparkSite"
      ]
    },
    "/services/fabrication-builds": {
      "global": "PageServicesFabricationBuilds",
      "bundle": "PageServicesFabricationBuilds",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/creative-design-studio": {
      "global": "PageServicesCreativeDesignStudio",
      "bundle": "PageServicesCreativeDesignStudio",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/trade-shows": {
      "global": "PageServicesTradeShows",
      "bundle": "PageServicesTradeShows",
      "deps": [
        "RelatedCases",
        "AiCaseStudies"
      ]
    },
    "/services/product-sampling": {
      "global": "PageServicesProductSampling",
      "bundle": "PageServicesProductSampling",
      "deps": [
        "RelatedCases"
      ]
    },
    "/spark-compare": {
      "global": "PageSparkCompare",
      "bundle": "PageSparkCompare",
      "deps": [
        "SparkSite"
      ]
    },
    "/compare": {
      "global": "PageCompare",
      "bundle": "PageCompare",
      "deps": []
    },
    "/spark-pricing": {
      "global": "PageSparkPricing",
      "bundle": "PageSparkPricing",
      "deps": [
        "SparkSite"
      ]
    },
    "/services/event-production": {
      "global": "PageServicesEventProduction",
      "bundle": "PageServicesEventProduction",
      "deps": [
        "RelatedCases"
      ]
    },
    "/best-experiential-marketing-agencies": {
      "global": "PageBestExperientialMarketingAgencies",
      "bundle": "PageBestExperientialMarketingAgencies",
      "deps": []
    },
    "/spark-trust": {
      "global": "PageSparkTrust",
      "bundle": "PageSparkTrust",
      "deps": [
        "SparkSite"
      ]
    },
    "/agency-of-record": {
      "global": "PageAgencyOfRecord",
      "bundle": "PageAgencyOfRecord",
      "deps": [
        "RelatedCases"
      ]
    },
    "/services/sponsorship-partnerships": {
      "global": "PageServicesSponsorshipPartnerships",
      "bundle": "PageServicesSponsorshipPartnerships",
      "deps": [
        "RelatedCases"
      ]
    },
    "/veteran-owned": {
      "global": "PageVeteranOwned",
      "bundle": "PageVeteranOwned",
      "deps": [
        "RelatedCases"
      ]
    },
    "/spark-solution": {
      "global": "PageSparkSolution",
      "bundle": "PageSparkSolution",
      "deps": [
        "SparkSite"
      ]
    },
    "/spark-explore": {
      "global": "PageSparkExplore",
      "bundle": "PageSparkExplore",
      "deps": [
        "SparkSite"
      ]
    },
    "/spark-use-case": {
      "global": "PageSparkUseCase",
      "bundle": "PageSparkUseCase",
      "deps": [
        "SparkSite"
      ]
    },
    "/spark-product": {
      "global": "PageSparkProduct",
      "bundle": "PageSparkProduct",
      "deps": [
        "SparkSite"
      ]
    },
    "/thank-you": {
      "global": "ThankYou",
      "bundle": "ThankYou",
      "deps": [],
      "props": {
        "rel": ""
      }
    }
  };
  var SERVICE = {
    "/services/brand-ambassador-management": "brand-ambassador-management",
    "/services/brand-strategy": "brand-strategy",
    "/services/buyer-pitch-line-reviews": "buyer-pitch-line-reviews",
    "/services/content-capture": "content-capture",
    "/services/crm-lifecycle": "crm-lifecycle",
    "/services/distribution-expansion": "distribution-expansion",
    "/services/event-reporting-recaps": "event-reporting-recaps",
    "/services/festival-brand-activations": "festival-brand-activations",
    "/services/fractional-sales-team": "fractional-sales-team",
    "/services/influencer-creator": "influencer-creator",
    "/services/logistics-kitting": "logistics-kitting",
    "/services/pop-up-retail": "pop-up-retail",
    "/services/qsr-restaurant-activations": "qsr-restaurant-activations",
    "/services/retail-readiness": "retail-readiness",
    "/services/retail-sales-broker-management": "retail-sales-broker-management",
    "/services/sports-marketing-activations": "sports-marketing-activations",
    "/services/sweepstakes-activations": "sweepstakes-activations",
    "/services/trade-marketing-management": "trade-marketing-management",
    "/travel": "travel",
    "/weddings": "weddings"
  };
  var SERVICE_DEPS = ["RelatedCases","MarketsData","ServicesData","ServiceDetail","ServicesDataExtra"];

  function currentPath() {
    var p = (location.pathname || "").replace(/\/+$/, "").toLowerCase();
    return p === "" ? "/" : p;
  }

  function loadScript(src, isLoaded) {
    return new Promise(function (resolve, reject) {
      if (typeof isLoaded === "function" && isLoaded()) return resolve();
      var existing = document.querySelector('script[data-ignite-src="' + src + '"]');
      if (existing) {
        if (existing.dataset.loaded === "1") return resolve();
        existing.addEventListener("load", function () { resolve(); });
        existing.addEventListener("error", function () { reject(new Error("failed " + src)); });
        return;
      }
      var s = document.createElement("script");
      s.src = src;
      s.setAttribute("data-ignite-src", src);
      s.onload = function () { s.dataset.loaded = "1"; resolve(); };
      s.onerror = function () { reject(new Error("failed " + src)); };
      document.head.appendChild(s);
    });
  }

  // load in order — later bundles read globals set by earlier ones
  function loadAll(names) {
    return names.reduce(function (chain, n) {
      return chain.then(function () { return loadScript(CDN + "/compiled/" + n + ".js"); });
    }, Promise.resolve());
  }

  function mountRoot() {
    var el = document.getElementById("page-root");
    if (el) return el;
    el = document.createElement("div");
    el.id = "page-root";
    var host = document.querySelector("main") || document.body;
    host.appendChild(el);
    return el;
  }

  function render(Comp, props) {
    if (!window.React || !window.ReactDOM) { console.error("[PagesRunner] React missing"); return; }
    if (!Comp) { console.error("[PagesRunner] component not found for " + currentPath()); return; }
    try {
      ReactDOM.createRoot(mountRoot()).render(React.createElement(Comp, props || null));
    } catch (err) {
      console.error("[PagesRunner] mount failed:", err);
    }
  }

  function run() {
    var p = currentPath();

    if (Object.prototype.hasOwnProperty.call(BESPOKE, p)) {
      var b = BESPOKE[p];
      loadAll((b.deps || []).concat([b.bundle]))
        .then(function () { render(window[b.global], b.props); })
        .catch(function (e) { console.error("[PagesRunner]", e); });
      return;
    }

    if (Object.prototype.hasOwnProperty.call(SERVICE, p)) {
      var slug = SERVICE[p];
      loadAll(SERVICE_DEPS)
        .then(function () { render(window.ServiceDetailPage, { slug: slug }); })
        .catch(function (e) { console.error("[PagesRunner]", e); });
      return;
    }
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", run, { once: true });
  else run();
})();
